version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABSE}
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql
    
  chatbot_api:
    build: 
      context: ./chatbot_api
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  chatbot_frontend:
    build: 
      context: ./chatbot_frontend
    env_file:
      - .env
    depends_on:
      - chatbot_api
    ports:
      - "8501:8501"
  
volumes:
  my-db: